notifications:
  slack:
    rooms:
      - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#pre-assignment
      - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#testing
    on_success: change
    on_failure: always
language: node_js
script:
  python thisshouldfail.py
  #echo Hello, this is a test message!
