deploy:
  provider: firebase
  token:
    secure: “T6WJKYCBDvT1cWRAbkMI7fWvC5vvEyTJQqai257vejaO27T22J2CKUKFhr1Zr9hBTyD1ygJvFw1N/M2iUCzRFpSIaiTNuXxynLlhTQUfW1Q6plZOp5dM/VaC++H0qtD2acAy2Jaqs6v7pk+qRvXMmkGHH1s4g9xUy5qT+2lVYOasscOgYNFnJ0Kc02XXYwFRJBxMjS8mkUzAxWMv8mWm3J7OZ6IRVLOZY5+yVaHFm+ZAGjhCEAqesopLPR68/rDzvqxqOWFcMbRDyC1iN/3G0re3pj2a1+9mSVcZpis1ZzndICmDFpsx8gZwvx9TuZfzjYQA817Ejnc+HHYgEo0CYgCpjSDBqGDZDsTlh8V9sfVn76NRovNbZ4Bs7oAerZ1uuWsnf1TNQ7QCOzjqT4GN2PFq4nkfSpBjpgkToFvGTCVxjjQ2EfEVCBpw/EKvT0MTDwuHKBeVQTvD/7WqZiXwjCHd0FsUSRZ6p5uu8hvNfGJptm3l9QExZhR7+Ycmq/uCX6W5jDTxoRATWOkyqL58b/crbdS+sgkeCPOuitdlIbwIr8p2Id12kufD3KE3i97ZwZyxGIO9suiOLVxLVihyvQae2/NhC3++drgzgB9Heh+qQZl466BKL/0l6IHvlt2twP6UfPfAQriwetnNrGCdBCfPsxFFggO+VDkfstXhLpc=”
notifications:
  email: false
  slack:
    rooms:
      - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#pre-assignment
      - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#testing
    on_success: change
    on_failure: always
language: node_js
script:
  echo Hello, this is a test message!
