notifications:
  slack:
    rooms:
      - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#testing
      - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#pre-assingment
      on_success: change
      on_failure: always
language: node_js
script:
  #echo Hello, this is a test message!
  python thisshouldfail.py
