notifications:
  email: false
  slack:
    rooms:
    - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#pre-assignment
    - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#testing
    on_success: change
    on_failure: always

language: node_js

node_js:
  # Specifying the latest Node.js version.
  "node"

before_script:
  - npm install -g gulp
  - npm install -g firebase-tools

addons:
 apt:
   packages:
     - oracle-java8-set-default

script:
  gulp

after_success:
  - ./deploy.sh
