deploy:
  provider: firebase
  token:
    secure: "PDozadoLuuhKmTR5F8OjKcP2tcGaBzygQs2Qj59GYgJeEdRsHyWeakfmekr/8KXqAEkwB2ea4tiqQUbWEm/7PVkqcfbW6ynn7jZmLsvOEIxmP9MN15AHMAojx0aWTrRQoSS1Y2szPgxqI67aTwinwI0wNguZiRaj0CzPtJFLBBfuiMV55thQKGPo7RexbCiMtQLRV1nj4Rtd97AJDevM7jn6vi0JPaeAUR++u+sHehnho7f1qeHNPg9vDFLbusMhQ+LtIZb8INAbnnOK3/pIHAI5JjACBpKC7IzTsPCoxJvvOgWkXULjDMpgIakZV5Vvvvh4ORaJfs6h4qx+EfWZqUztPXkYdhkg6/hD6URTdoPpV38UfqvA5IxL+s6A3NFQqngRCMgcLl3+cezK1cG0gCdwmdwzGXz5vjVP22qPs47nK9z11BUsSdR6qZh4aOdlbHTIV9Optj/CRh3yWwC612HLZuiNObGIPVEXzJkggPLviMtr+HlEoddsKCUt5uSkhGbYx7zXY2Ir05Za9UEQ9L11gkMpgZ2oh+5ZJryjRN0sWBcGPgqLyRTHwMw2O5KVzFOuCTTUuMWeyEkBtrrIqU/GKWI0bFNVMr7to8gPQoPHgOO3olYglmOlBVZH6kiQ+yj7HwzyN6jHIFrumKyo6aU4NXQR9E/KhgoD4m7+eXc="
  project: alpha-team-84c76
notifications:
  email: false
  slack:
    rooms:
    - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#pre-assignment
    - cse112-alphateam:bjfz7Qlh7uNaWemWc2Khf6wS#testing
    on_success: change
    on_failure: always
language: node_js
script: echo Hello, this is a test message!
